### ISSUE TITLE
Make ExecutionTimingExecutionListener compatible with existing ExecutionListener

### ISSUE THREAD

**Issue by leonard84** [timgifford/maven-buildtime-extension#19]
Jenkins injects its own `ExecutionListener` to extract information about the build. Since `MavenExecutionRequest` supports only one `ExecutionListener` it is currently overwritten by ExecutionTimingExecutionListener. 

We could either use a delegating pattern similar to
https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/eventspy/internal/EventSpyExecutionListener.java or directly use the EventSpy mechanism https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/eventspy/AbstractEventSpy.java

From what I've seen extending AbstractEventSpy is the right way to go.

**Comment by leonard84** [comment]
@timgifford I've started the refactoring here https://github.com/leonard84/maven-buildtime-extension/tree/refactor-to-eventspy

However for some reason it does not work anymore if the extension is defined in the pom. It must either be added via `-Dmaven.ext.class.path=...` or preferably via the `.mvn/extensions.xml` file.

I think the benefits outweigh the downside of it not working in the pom extension section anymore.
While I was refactoring, I also decoupled the reporting from the tracking and added Maven Invoker integration tests.

**Comment by nudgegoonies** [comment]
+1

**Comment by leonard84** [comment]
@timgifford any comment?

**Comment by mfriedenhagen** [comment]
+1

**Comment by mfriedenhagen** [comment]
@leonard84, did you check, wether including in a pom works with Maven 3.3.9 again?

**Comment by timgifford** [comment]
@leonard84 
I love the maven invoker integration tests. I followed your lead and spiked on them in the publisher-spike branch.
I like the eventspy model. Thanks for discovering that. I think I tried to integrate that in the spike,
but there doesn't appear to be a way to register the extension when it's defined in the pom.xml.

I really want the extension to be in the pom.xml for a few reasons: 
 * build timing is project specific
 * simple/intuitive configuration
 * "Tim Proof" distribution 

**Project Specific**
Tracking build time seems like something I don't always want by default. Placing it as an extension makes it system specific. Making it system wide might harm adoption.

** Configuration **
When it's in the pom, configuration is in the pom. It is where I expect to find configuration project based settings. I want to minimize any need for documentation to use the extension. My philosophy is that the extension should work with sensible default and shouldn't require specific parameters to run.

** Distribution **
Maven has made us lazy. It's is so easy to get all the dependencies for a project when there is a pom.xml. Requiring users to manually grab the jar and place in a special directory makes distribution more difficult.

Just opinions, but ease of use is really important to me. Anybody should be able to find the project and get it running within 5 minutes.

**Comment by leonard84** [comment]
@timgifford the only real downside from not having it in the pom is that you can't inherit it, but as I said you can/should use the `.mvn/extensions.xml` which lives inside your project. So it is project specific and you only need to declare the same stuff which you would declare in the pom. That is what I'm using in the integration tests (https://github.com/leonard84/maven-buildtime-extension/blob/refactor-to-eventspy/src/it/both-it/.mvn/extensions.xml).

Having it in the pom also has the downside of wanting to use profiles, at least it had for me, only to discover that you can do very little with extensions in terms of configurations/profiles, so this separation might actually be a good thing. And distribution is even simpler, just drop the `extension.xml` in a project folder and you are good to go.

**Comment by timgifford** [comment]
Ok. I didn't realize that .mvn/extensions.xml was within the project
directory. That should work. Thank you for helping me understand.

On Tue, Feb 2, 2016 at 3:17 PM, Leonard Brünings <notifications@github.com>
wrote:

> @timgifford <https://github.com/timgifford> the only real downside from
> not having it in the pom is that you can't inherit it, but as I said you
> can/should use the .mvn/extensions.xml which lives inside your project.
> So it is project specific and you only need to declare the same stuff which
> you would declare in the pom. That is what I'm using in the integration
> tests (
> https://github.com/leonard84/maven-buildtime-extension/blob/refactor-to-eventspy/src/it/both-it/.mvn/extensions.xml
> ).
>
> Having it in the pom also has the downside of wanting to use profiles, at
> least it had for me, only to discover that you can do very little with
> extensions in terms of configurations/profiles, so this separation might
> actually be a good thing. And distribution is even simpler, just drop the
> extension.xml in a project folder and you are good to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timgifford/maven-buildtime-extension/issues/19#issuecomment-178825546>
> .
>



-- 
Tim Gifford
mobile: 515.419.1909
twitter: @timgifford
linkedin: http://www.linkedin.com/in/timgifford/
github: https://github.com/timgifford

**Comment by leonard84** [comment]
I've opened a PR #20

**Comment by leonard84** [comment]
PR is merged -> close
