### ISSUE TITLE
Add travis for CI

### ISSUE THREAD

**Issue by leonard84** [timgifford/maven-buildtime-extension#22]
Since we now have some rather useful unit and integration tests, I would suggest adding https://travis-ci.org/ so that PRs are automatically checked. See https://docs.travis-ci.com/user/getting-started

**Comment by timgifford** [comment]
Great suggestion. I've started this. Hopefully get it setup this weekend.

**Comment by timgifford** [comment]
Hooked up and running...unfortunately currently failing, but that is a different issue.
