### ISSUE TITLE
Will there ever be 3.0.2 release?

### ISSUE THREAD

**Issue by inikolaev** [timgifford/maven-buildtime-extension#31]

**Comment by leonard84** [comment]
only @timgifford can build one

**Comment by timgifford** [comment]
I'll get one released this weekend...possibly earlier.

**Comment by timgifford** [comment]
Freshly published. Enjoy!
https://oss.sonatype.org/service/local/repositories/releases/content/co/leantechniques/maven-buildtime-extension/3.0.2/maven-buildtime-extension-3.0.2.jar

**Comment by inikolaev** [comment]
Great, thanks!
